apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: caddy-ingress-controller
  labels:
    k8s-app: caddy-ingress-controller
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: caddy-ingress-controller
      namespace: kube-system
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - image: zikes/caddy-ingress:0.0.1
          name: caddy-ingress-controller
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /healthz
              port: 12015
              scheme: HTTP
          livenessProbe:
            httpGet:
              path: /healthz
              port: 12015
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 1
          ports:
          - containerPort: 80
            hostPort: 80
          - containerPort: 443
            hostPort: 443
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          args:
          - /caddy-ingress-controller
          - --default-backend-service=$(POD_NAMESPACE)/default-http-backend
