kind: Service
apiVersion: v1
metadata:
  name: caddy-ingress
  namespace: kube-system
  labels:
    k8s-app: caddy-ingress-controller
spec:
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
  selector:
    k8s-app: caddy-ingress-controller
